### ISSUE TITLE
Horizontal scroll problem with pages having vertical scroll

### ISSUE THREAD

**Issue by hi-Kartik2004** [shuxton/GDSC-Angular#16]
## Horizontal scroll problem

![image](https://user-images.githubusercontent.com/111000515/212717263-511c7712-1092-4d8b-a302-b55fb5b4a614.png)

#### Replacing navbar width: 100vw with 100% would solve the problem.

**Comment by Shivamrut** [comment]
can you briefly explain what the problem is. I dont see any need of a horizontal bar

**Comment by hi-Kartik2004** [comment]
Hi @Shivamrut, the problem is not with your code, as stated in the message it was the nav-bar problem that has been resolved in the previous commit.

**Comment by hi-Kartik2004** [comment]
Issue resolved in PR #18
