### ISSUE TITLE
⚠️ ⚠️ Two entries have same id

### ISSUE THREAD

**Issue by hi-Kartik2004** [shuxton/GDSC-Angular#7]
## As seen, line number 23 must-have id : 6

![image](https://user-images.githubusercontent.com/111000515/212529301-d2d494e3-5b1f-4bca-a36a-c1bf738139cd.png)

![image](https://user-images.githubusercontent.com/111000515/212529333-f980fe9b-0101-4ea2-a7ef-1c00ca345fc2.png)

**Comment by shuxton** [comment]
issue has been resolved
